name: Build and Push to ECR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:                
    runs-on: ubuntu-latest       
    
    steps:                       
    - name: Check out code       
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: autoever-guestbook
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: Checkout Manifest Repository
      uses: actions/checkout@v3
      with:
        repository: Yeonhee-Kim/k8s-manifests # 실제 매니페스트 레포 주소
        token: ${{ secrets.MANIFEST_TOKEN }} # 방금 등록한 시크릿 이름
        path: k8s-manifests # 작업 공간 내 폴더 이름

    - name: Update Kubernetes resources
      run: |
        cd k8s-manifests/manifests
        # deployment.yaml 파일에서 이미지 태그 부분을 이번 빌드 태그(${{ github.sha }})로 변경
        sed -i "s|image:.*|image: ${{ steps.login-ecr.outputs.registry }}/autoever-guestbook:${{ github.sha }}|g" deployment.yaml
        
        # 변경사항 깃허브에 푸시
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        git add deployment.yaml
        git commit -m "Update image tag to ${{ github.sha }} [skip ci]"
        git push origin main
